export { default as Hero } from './Hero'
export { default as WhyChooseUs } from './WhyChooseUs'
export { default as Portfolio } from './Portfolio'
export { default as Testimonials } from './Testimonials'
export { default as Contact } from './Contact'